language: node_js
node_js:
  - "5.1.1"
before_install:
  - npm install -g bower
  - npm install -g nw-builder
  - cd app/
  - bower install
  - cd ..
script:
  - npm install
  - nwbuild -v 0.12.3 -p osx32,osx64,win32,win64,linux32,linux64 .
